export const RECITE_COMPLETE_FAIL = "[MEMORIZE] RECITE_COMPLETE_FAIL";
export const RECITE_COMPLETE_SUCCESS = "[MEMORIZE] RECITE_COMPLETE_SUCCESS";
export const RECITE_NEXT_NUMBER = "[MEMORIZE] RECITE_NEXT_NUMBER";
export const RECITE_START = "[MEMORIZE] RECITE_START";

export const INTRO_START = "[MEMORIZE] INTRO_START";
export const INTRO_NEXT_NUMBER = "[MEMORIZE] INTRO_NEXT_NUMBER";
export const INTRO_END = "[MEMORIZE] INTRO_END";

export const GOTO_FAIL_SCREEN = "[MEMORIZE] GOTO_FAIL_SCREEN";
export const GOTO_SUCCESS_SCREEN = "[MEMORIZE] GOTO_SUCCESS_SCREEN";
export const GOTO_INTRO_SCREEN = "[MEMORIZE] GOTO_INTRO_SCREEN";
export const GOTO_HOME_SCREEN = "[MEMORIZE] GOTO_HOME_SCREEN";
export const GOTO_RECITE_SCREEN = "[MEMORIZE] GOTO_RECITE_SCREEN";
export const GOTO_SETTINGS = "[MEMORIZE] GOTO_RECITE_SCREEN";
