
export const FAIL_SCREEN = "[MEMORIZE] FAIL_SCREEN";
export const SUCCESS_SCREEN = "[MEMORIZE] SUCCESS_SCREEN";
export const INTRO_SCREEN = "[MEMORIZE] INTRO_SCREEN";
export const SETTINGS_SCREEN = "[MEMORIZE] SETTINGS_SCREEN";
export const HOME_SCREEN = "[MEMORIZE] HOME_SCREEN";
export const RECITE_SCREEN = "[MEMORIZE] RECITE_SCREEN";
export const DEFAULT_SCREEN = HOME_SCREEN;